### ISSUE TITLE
TOD always publishes empty detection messages

### ISSUE THREAD

**Issue by jordi-pages** [wg-perception/tod#4]
When running TOD as follows:

```
rosrun object_recognition_core detection -c `rospack find object_recognition_tod`/conf/detection.ros.ork --visualize
```

Even when it seems that the detector has found an object pose:

```
***Starting object: 0
23 keypoints in 29 matches
done filling
RANSAC done with 6 inliers
RANSAC done with 0 inliers
********************* found 1 poses
```

The /recognized_object_array always shows the same contents, i.e.:

```
header: 
  seq: 436
  stamp: 
    secs: 1389699270
    nsecs: 108067246
  frame_id: ''
objects: []
cooccurrence: []
```
